updated the ReadMe file
AsimKhan2019/video_youtube pull request #3
Opened 2022-05-30 09:30 UTC by AsimKhan2019

Updated the Read Me File

2022-05-30 09:32 UTC, AsimKhan2019 commented
Leaving the request open for review

2022-05-30 09:36 UTC, Munsa1 requested changes
Hi @AsimKhan2019 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no review from you. You are supposed to review your work like a code reviewer does.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-30 09:52 UTC, AsimKhan2019 commented
@Munsa1 Thank you for the guideline. I have just added some reviews to the Read Me File.

2022-05-30 09:52 UTC, AsimKhan2019 commented
@Munsa1 Please tell me if this is ok.

2022-05-30 11:04 UTC, KayLemba requested changes
Hi @AsimKhan2019    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 - Please add Proffessional and descriptive PULL REQUEST 
- Please use github inline comment to add reviews and changes to you past project from the trial. In short please review your project and add some comments on what you didnt do correctly. Kindly read through the project requirement properly for a better understanding. Thanks 
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 12:05 UTC, AsimKhan2019 commented
@KayLemba Thank you for the guidelines. I wanted some clarity, I have added inline reviews to the code. Can you please provide some more clarity? As for the trials, this is the project I did in the past and made some adjustments to the project. Kindly please provide some more guidelines.

2022-05-30 12:09 UTC, KayLemba commented
There is a lesson on this in the material provided by microverse please kindly go through it. check your notes

2022-05-30 12:10 UTC, KayLemba commented
You need to give yourself a review

2022-05-30 14:32 UTC, AsimKhan2019 commented
@KayLemba I think I understand what you mean. Can you please look at the repository now, and see if this is correct?

2022-05-31 06:31 UTC, AsimKhan2019 commented
@KayLemba How about now? I have gone through the tutorial. I have made some adjustments to the code review. Please let me know your thoughts.

2022-05-31 07:04 UTC, ishimwezachee commented
> @KayLemba How about now? I have gone through the tutorial. I have made some adjustments to the code review. Please let me know your thoughts.

Hello @AsimKhan2019 , I am your second reviewer, are you there so that we can have a little chat ?

2022-05-31 07:06 UTC, AsimKhan2019 commented
@ishimwezachee Yes I am here, I am in a morning session meeting and will be free shortly.

2022-05-31 07:31 UTC, ishimwezachee requested changes
Hi @AsimKhan2019 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
Hi @AsimKhan2019 , as the first review asked, just implement the inline comments, and I guess the [videos ](https://www.loom.com/share/1d60a88c8ac543fe84764aaa7c51dc7a)I have made to guide you will help you. 


## Highlights


## Required Changes ♻️
![image](https://user-images.githubusercontent.com/43877689/171117412-4f5e4eed-74da-462e-8107-9658dda7b52d.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 08:03 UTC, AsimKhan2019 reviewed
You have done a great job. There are a few changes still needed. Have them reviewed, and keep up the good work. 

Cheers!

2022-05-31 08:03 UTC, AsimKhan2019 commented on README.md
- [ ] Nicely done putting in the link for review.

2022-05-31 08:03 UTC, AsimKhan2019 commented on index.html
> +              allowfullscreen></iframe> <!-- removed frameborder -->
- [ ]  You have applied the right approach here. The frame border attribute is obsolete.

2022-05-31 08:03 UTC, AsimKhan2019 commented on style.css
>    padding-left: 25px;
- [ ] You have added in the header tag element, which is a good practice. Let's use numeric pixel values for font size instead, that is much better.

2022-05-31 08:03 UTC, AsimKhan2019 commented on README.md
> +https://htmlpreview.github.io/?https://github.com/AsimKhan2019/video_youtube/blob/main/index.html
- [ ] I think it is better to use some better formatting styles for the link

2022-05-31 08:03 UTC, AsimKhan2019 commented on index.html
>        <header id="header">
- [ ] You have applied the right approach using header tags instead of div tags.

2022-05-31 08:03 UTC, AsimKhan2019 commented on style.css
>    padding-left: 25px;
- [ ] You have done well so far, now let's use numeric pixel for font size.

2022-05-31 08:03 UTC, AsimKhan2019 commented on style.css
>    width: 590px;
- [ ] Try using percentages for width size, instead of pixels. It helps with the resolution.

2022-05-31 08:18 UTC, muneebulrehman approved these changes
Hi @AsimKhan2019 

Great job on figuring out how to use inline comments. You would need them more than you think. Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 08:59 UTC, AsimKhan2019 commented
@muneebulrehman Thank you for the feedback.

2022-05-31 08:59 UTC, merged